{
 "title": "CRC_Monitoring",
 "description": "Basic dashboard for monitoring System, Api and database",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "release",
    "label": "Release",
    "query": {
     "query": "query_result(pg_exporter_last_scrape_duration_seconds{kubernetes_namespace=\"$namespace\"})"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(pg_up{release=\"$release\"})"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(pg_exporter_last_scrape_duration_seconds)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Sys", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"localhost:9100\", job=\"node_exporter\"} / node_memory_MemTotal_bytes{instance=\"localhost:9100\", job=\"node_exporter\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sys Load",
   "type": "gauge",
   "description": "System load  over all CPU cores together",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{instance=\"localhost:9100\",job=\"node_exporter\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"localhost:9100\",job=\"node_exporter\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"localhost:9100\",job=\"node_exporter\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"localhost:9100\",job=\"node_exporter\"} - node_boot_time_seconds{instance=\"localhost:9100\",job=\"node_exporter\"}"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Numbers of passing queries (2xx)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "irate(http_requests_total{handler=\"/api/v1/applications/{id}\", method=\"GET\", status=\"2xx\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Numbers of not passing queries (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "irate(http_requests_total{handler=\"/api/v1/applications/{id}\", method=\"GET\", status=\"5xx\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(irate(http_request_duration_seconds_sum[1m]))/sum(irate(http_requests_total[1m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "(sum (irate(http_requests_total{handler=\"/api/v1/applications/{id}\", method=\"GET\", status=\"5xx\"}[1m]))/\nsum (irate(http_requests_total[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_static{release=\"$release\", instance=\"$instance\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{release=\"$release\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{state=\"active\"}\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}