
global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - 'rules/alert.yml'

alerting:
  alertmanagers:
  - static_configs:
     - targets:
       - 'localhost:9093'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

  - job_name: "grafana"
    honor_labels: true
    static_configs:
      - targets: ['localhost:3000']
        labels:
          machine: crc_centos

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['localhost:9187']

  - job_name: 'crcapi'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/metrics'
