name: crc_sre workflow

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  config_monitoring:
    runs-on: ubuntu-latest
    steps:
    
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          run: |
            whoami
            echo "switch to root"
            sudo su
            sudo useradd -m -s /bin/bash prometheus
            sudo chown -R prometheus:prometheus /home/prometheus/
            mkdir -p /etc/crc_files/
            exit
          
      - uses: actions/checkout@v3   
      - name: copying files
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "alerts.yml,grafana_install.sh,postgres_exporter.env,prometheus.yml,prometheus_install.sh"
          target: /tmp/crc/

      - name: create alert file
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          run: |
            echo "switch to root"
            sudo su
            sudo cat > /tmp/crc_files/alertmanager.yml << EOF
            global:
              resolve_timeout: 1m

            route:
              group_by: ['alertname']
              group_wait: 10s
              group_interval: 10s
              repeat_interval: 1h
              receiver: 'email_notifications'
            receivers:
              - name: 'email_notifications'
              email_configs:
              - to: ${{ secrets.MAILTO }}
                from: alerttesting2288@outlook.com
                smarthost: smtp.outlook.com:587
                auth_username: alerttesting2288@outlook.com
                auth_identity: alerttesting2288@outlook.com
                auth_password: alerttesting1234
                send_resolved: true
            EOF
            
                    
            inhibit_rules:
              - source_match:
                  severity: 'critical'


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
