name: crc_sre workflow

on:
  workflow_dispatch:

jobs:
  config_monitoring:
    runs-on: ubuntu-latest
    steps:
    
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          run: |
            whoami
            echo "switch to root"
            sudo su
            sudo useradd -m -s /bin/bash prometheus
            sudo chown -R prometheus:prometheus /home/prometheus/
            mkdir -p /tmp/conf_files/
            exit
          
      - uses: actions/checkout@v4   
      - name: copying files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "alerts.yml,grafana_install.sh,postgres_exporter.env,prometheus.yml,prometheus_install.sh"
          target: /tmp/conf_files/

      - name: create alert file
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            echo "switch to root"
            sudo su
            sudo cat > /tmp/conf_files/alertmanager.yml << EOF
            global:
              resolve_timeout: 1m
              
            route:
              group_by: ['alertname']
              group_wait: 10s
              group_interval: 10s
              repeat_interval: 1h
              receiver: 'email_notifications'
              
            receivers:
              - name: 'email_notifications'
              email_configs:
              - to: ${{ secrets.EMAIL_TO }}
                from: ${{ secrets.EMAIL_FROM }}
                smarthost: ${{ secrets.SMARTHOST }}
                auth_username: ${{ secrets.EMAIL_FROM }}
                auth_identity: ${{ secrets.EMAIL_FROM }}
                auth_password: ${{ secrets.EMAIL_PASS }}
                send_resolved: true  
                
            inhibit_rules:
              - source_match:
                  severity: 'critical'
            EOF
            exit

      - name: Execute scripts
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            echo "Executing scripts"
            sudo su
            chmod +x /tmp/conf_files/prometheus_install.sh
            cd /tmp/conf_files/
            ./prometheus_install.sh

            chmod +x /tmp/conf_files/grafa_install.sh
            cd /tmp/conf_files/
            ./grafana_install.sh
            exit
            

      # Runs a set of commands using the runners shell
      - name: Start services
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            sudo su
            echo "enable services"
            systemctl enable prometheus.service node_exporter.service postgres_exporter.service
            echo "start services and check status"
            systemctl start prometheus.service node_exporter.service postgres_exporter.service alertmanager.service
            systemctl status prometheus.service node_exporter.service postgres_exporter.service alertmanager.service
            exit
